# Generated by Django 4.2.7 on 2023-11-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba1', '0003_raza_remove_cita_gender_pet_remove_cita_race_pet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='celular',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='documento',
            field=models.CharField(max_length=30),
        ),
    ]
